alt_logo: "Rails logo"
avatar:
  size:
    default: 80
    for_list: 50
    for_follow: 30
email:
  length:
    min: 11
    max: 50
  valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  expired_hours: 2
image_type: ["image/jpeg", "image/gif", "image/png"]
image_type_accepted: "image/jpeg,image/gif,image/png"
image_resize: [500, 500]
link:
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  rails_home: "http://www.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  learn_enough: "https://www.learnenough.com/"
  screencast_series: "https://screencasts.railstutorial.org/"
  rails_contact: "https://www.railstutorial.org/contact"
  gravatar_home: "https://gravatar.com/emails"
max_image_storage_size: 5
max_item_per_page: 5
micropost:
  length:
    max: 140
  one_page: 10
  avatar:
    size: 50
name:
  length:
    min: 3
    max: 50
password:
  length:
    min: 6
page:
  item_per_page: 15
user:
  admin:
    name: "Example User"
    email: "example@railstutorial.org"
    password: "foobar"
  faker:
    password: "password"
