alt_logo: "Rails logo"
link:
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  rails_home: "http://www.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  learn_enough: "https://www.learnenough.com/"
  screencast_series: "https://screencasts.railstutorial.org/"
  rails_contact: "https://www.railstutorial.org/contact"
  gravatar_home: "https://gravatar.com/emails"
name:
  length:
    min: 3
    max: 50
email:
  length:
    min: 11
    max: 50
  valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  expired_hours: 2
password:
  length:
    min: 6
avatar:
  size:
    default: 80
    for_list: 50
page:
  item_per_page: 15
user:
  admin:
    name: "Example User"
    email: "example@railstutorial.org"
    password: "foobar"
  faker:
    password: "password"
