alt_logo: "Rails logo"
link:
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  rails_home: "http://www.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  learn_enough: "https://www.learnenough.com/"
  screencast_series: "https://screencasts.railstutorial.org/"
  rails_contact: "https://www.railstutorial.org/contact"
